/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 blue.glb --transform
Author: Kugatsu Tsukai 3D Models Hub (https://sketchfab.com/KugatsuT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-diamond-free-giveaway-618d614891354c1f86f07845080e13e7
Title: Blue Diamond - Free Giveaway
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export default function Blue(props) {
  const { nodes, materials } = useGLTF("/blue-transformed.glb");
  const { position } = useControls("Blue", {
    position: {
      value: [0, 0, 0],
      step: 0.1,
    },
  });

  return (
    <group scale={2} {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.DiamondOutside}
      />
    </group>
  );
}

useGLTF.preload("/blue-transformed.glb");
